version: '3'
services:
  jekyll:
    container_name: thebrotales
    image:  jekyll/jekyll:pages
    environment: 
      JEKYLL_ENV: docker
    command: jekyll serve --watch --force_polling --verbose --livereload --port 4001
    ports:
      - 4001:4001
      - 35729:35729
    volumes:
      - .:/srv/jekyll