version: '3'
services:
  jekyll:
    container_name: thebrotales
    image: jekyll/jekyll:4.2.0
    environment: 
      JEKYLL_ENV: docker
    command: jekyll serve --watch --force_polling --verbose --livereload --port 4001 --livereload-port 35728
    ports:
      - 4001:4001
      - 35728:35728
    volumes:
      - .:/srv/jekyll