on:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '30 5,17 * * *'
  push:


jobs: 
  check-gh-pages-ip:
    runs-on: ubuntu-latest
    steps: 
      - name: Check GitHub API for GitHub Pages IP's
        id: get_current_ip
        run: |
          current_ip_addr=$(curl https://api.github.com/meta | jq '.pages[0]')
          echo $current_ip_addr
          echo "::set-output name=current_ip_addr::$current_ip_addr"
      
      - name: All happy
        if:  ${{ contains( steps.get_current_ip.outputs.current_ip_addr , secrets.CURRENT_GITHUB_PAGES_IP) }}
        run: |
          echo "Yea, it works"
        
      - name: Send out SOS to update
        if:  ${{ !contains( steps.get_current_ip.outputs.current_ip_addr , secrets.CURRENT_GITHUB_PAGES_IP) }}
        uses: dawidd6/action-send-mail@v3
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          username: '${{secrets.MAIL_USERNAME}}'
          password: '${{secrets.MAIL_PASSWORD}}'
          subject: [TheBROTales] Afrihost/GitHub needs fixing
          to: dexfitz5@gmail.com
          from: GitHub Actions Bot # <user@example.com>
          secure: true
          body: IP ranges checker job of ${{ github.run_id}} in ${{github.repository}} failed!
          html_body: 
          cc: 
          bcc: 
          reply_to: 
          in_reply_to: 
          ignore_cert: true
          convert_markdown: true
          attachments: 
          priority: low- name: Send mail
