on:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '30 5,17 * * *'
  push:


jobs: 
  check-gh-pages-ip:
    runs-on: ubuntu-latest
    steps: 
      - name: Check GitHub API for GitHub Pages IP's
        id: get_current_ip
        run: |
          current_ip_addr=$(curl https://api.github.com/meta | jq '.pages[0]')
          echo $current_ip_addr
          echo "::set-output name=current_ip_addr::$current_ip_addr"
      
      - name: All happy
        if: ${{ contains( steps.get_current_ip.outputs.current_ip_addr, 192.30.252.153) }}
        id: all_happy
        run: |
          echo "Yea, it works"

      - name: Checkout repo
        if: ${{ !contains( steps.get_current_ip.outputs.current_ip_addr, 192.30.252.153) }}
        uses: actions/checkout@v3
        id: checkout_repo
        with:
          repository: '${{ github.repository }}'
          ref: 'gh-pages'
          token: ' ${{ github.token }}'

      - name: Send out SOS to update
        if: ${{ !contains( steps.get_current_ip.outputs.current_ip_addr, 192.30.252.153) }}
        uses: dawidd6/action-send-mail@v3
        id: send_mail
        with:
          server_address: "smtp.gmail.com"
          server_port: 465
          username: '${{ secrets.MAIL_USERNAME }}'
          password: '${{ secrets.MAIL_PASSWORD }}'
          subject: (TheBROTales) Afrihost/GitHub needs fixing 
          to: '${{ secrets.MAIL_TO_USERNAME }}'
          from: '${{ secrets.MAIL_USERNAME }}'
          secure: true
          ignore_cert: true
          html_body: file://.github/workflows/email.html
          priority: low
